### ISSUE TITLE
Reddit Gallery downloading

### ISSUE THREAD

**Issue by josephrcox** [josephrcox/easy-reddit-downloader#31]
Right now, reddit gallery links are just handled like links. 

We need a way to parse that it's a gallery (should be easy), and then iterate over the media in the gallery, downloading 1 by 1.

**Comment by Jay4242** [comment]
I don't know any nodejs so I wrote [a bash script](https://gist.github.com/Jay4242/427aa460807f2456bbeeddef0a58758f) that uses yt-dlp & gallery-dl to try to download things.

**Comment by josephrcox** [comment]
Thanks for that @Jay4242. I wonder if I can use a similar packing to yt-dlp to download these in Node
