### ISSUE TITLE
Ability to download all subreddit posts, rather than a set number

### ISSUE THREAD

**Issue by josephrcox** [josephrcox/easy-reddit-downloader#4]

**Comment by mapleweekend** [comment]
Closing as this is closely related to the recently completed issue #18

**Comment by etec-masterofsynapse** [comment]
Did you introduce a new label to download all posts of a subreddit?
Simply because the program can handle more than 100 posts at once, doesn't mean this issue / FR is solved.
An "all" for the post count question would go a long way for easy archiving of subreddits.

**Comment by josephrcox** [comment]
I just added a number. But you can set a ridiculous number and it will stop if there are no posts left. I can reopen and add an "all" qualifier to just keep going until there aren't any left

**Comment by josephrcox** [comment]
@etec-masterofsynapse added option for "all"! https://github.com/josephrcox/easy-reddit-downloader/releases/tag/v0.1.6 try it out and let me know if you have any issues with it
