### ISSUE TITLE
Date/Author in file name?

### ISSUE THREAD

**Issue by Jay4242** [josephrcox/easy-reddit-downloader#49]
Would it be possible to have an option to put the date or author at the start of the file name?  Preferably YYYY-MM-DD for the date so it sorts properly.

Thanks.

**Comment by josephrcox** [comment]
I got it working with customizable titles with date created, author, and post title as options. Just confirm with me @Jay4242 if this is what you were looking for! 

<img width="323" alt="image" src="https://user-images.githubusercontent.com/73198556/211708230-db2b5486-9561-47df-8c37-d717b38865e2.png">

**Comment by josephrcox** [comment]
Thanks for your suggestion! This feature is now added and available. Please download v0.1.8 and let me know what you think! 🎉 

https://github.com/josephrcox/easy-reddit-downloader/releases/tag/v0.1.8 or `git pull` should do it

**Comment by Jay4242** [comment]
Great!  Yep, that seems to take care of it, thanks!

**Comment by josephrcox** [comment]
You're welcome!
