### ISSUE TITLE
Memory usage spike?

### ISSUE THREAD

**Issue by Jay4242** [josephrcox/easy-reddit-downloader#61]
Does anybody else get random spikes of memory usage?
I just noticed this on my machine running it, (htop output)
![Screenshot_2023-01-18_08-03-11](https://user-images.githubusercontent.com/96741732/213227620-4ad85712-62d0-4ae0-ad16-9105efda831b.png)
25G virt resources.  53% of memory (before output froze).
It's currently swapping, I figure it'll get killed eventually...

edit: as a workaround I made an expect script that looks for the sleep time I set,
```
#!/usr/bin/expect -f
set timeout -1
spawn node index.js
expect -ex "Waiting 1800 seconds"
send "kill -9 \$\$\r"
```
So it'll kill it then I wrap that in a loop and sleep 1800 seconds.

**Comment by josephrcox** [comment]
This is odd. @Jay4242 Are you still facing the issue? I was waiting to see if anyone else has the same issue.
