### ISSUE TITLE
Large amount of Post temporary banning IP

### ISSUE THREAD

**Issue by Jon1Games** [josephrcox/easy-reddit-downloader#83]
Hello,
I tried to used the downloader with an large amount of post and it temporary banned my IP... I figured out i woud be enough to add an Sleep funktion:
```
function Sleep(milliseconds) {
	return new Promise(resolve => setTimeout(resolve, milliseconds));
}
```
and use it at the start off the for loop:
```
for (let i = 0; i < lines.length; i++) {
	await Sleep(250); // new Sleeptimer for avoid being temporary IP banned (1000 = 1sek)
	const line = lines[i];
       // more code
       }
```
This is just an personal solution, and isn´t really configurable without working with cod.
(an sleeptimer of 256 milisecounds shoud be enough for not being kicked, but can be lesser ig)

**Comment by josephrcox** [comment]
How do you know they temporarily banned your IP? Do you have a log that you are able to share?

**Comment by Jon1Games** [comment]
sure, buts a verylong error so i just copy the part that say´s it temporary blocked (saw that it sayed "blocked" now but still does the same ig)

```
    data: '<!doctype html>\n' +
      '<html>\n' +
      '  <head>\n' +
      '    <title>Too Many Requests</title>\n' +
      '    <style>\n' +
      '      body {\n' +
      '          font: small verdana, arial, helvetica, sans-serif;\n' +
      '          width: 600px;\n' +
      '          margin: 0 auto;\n' +
      '      }\n' +
      '\n' +
      '      h1 {\n' +
      '          height: 40px;\n' +
      '          background: transparent url(//www.redditstatic.com/reddit.com.header.png) no-repeat scroll top right;\n' +
      '      }\n' +
      '\n' +
      '      textarea.mushroom {\n' +
      '          display: none\n' +
      '      }\n' +
      '    </style>\n' +
      '  </head>\n' +
      '  <body>\n' +
      '    <h1>whoa there, pardner!</h1>\n' +
      '\n' +
      "<p>reddit's awesome and all, but you may have a bit of a\n" +
      "problem. we've seen far too many requests come from your ip address\n" +
      'recently.</p>\n' +
      '\n' +
      '<p>please wait a few minutes and try again.</p>\n' +
      '\n' +
      "<p>if you're still getting this error after a few minutes and\n" +
      "think that we've incorrectly blocked you or you would like to discuss\n" +
      'easier ways to get the data you want, please contact us at <a href=mailto:ratelimit@reddit.com?Subject=Rate%20limiting(C)%20of%2084.118.219.14 (Request ID: 3943415873-FRA)>this email address</a>.</p>\n' +    
      '\n' +
      "<p>You can read Reddit's Terms of Service <a href=https://www.reddit.com/wiki/api/>here</a>.</p>\n" +
      '\n' +
      '<p>when contacting us, please include your ip address which is: <strong>84.118.219.14</strong> and reddit account</p>\n' +
      '\n' +
      '</body>\n' +
      '</html>'
  }
```

**Comment by josephrcox** [comment]
Thanks!! I am not sure how we can deal with this sadly without knowing the way that Reddit identifies an IP address as **too** active. We could delay requests by 250ms like you suggested which may help, but it also may not depending on how Reddit identifies this. 

I will add something and we can see how well it works!

**Comment by josephrcox** [comment]
@Jon1Games Can you please try the newest index.js file? I added a sleep call that waits for 250ms between calls. Let me know if this helps or doesn't help!

**Comment by Jon1Games** [comment]
Now the error appears after downloading about 200 posts. Earlyer was 80, I think, so I would recommend making a description for it in the redme so the user can decide how high the delay should be and also give some examples like:
0 = up to 80
250 = up to 200
...
I think I used 1000 for an 800 download list. (but not sure about it)

Another option would be to read out the number of lines in the text and decide which delay is used.

**Comment by Jon1Games** [comment]
Currently, your edits just delay the start of the download without adding a delay between the downloads. I think you need to make the delay inside the for loop (line 591) to correctly affect the delay between the downloads.

**Comment by Jon1Games** [comment]
I dont really know how to make something you can accept merging with your github project, so I just forked your project and uploaded my changes so you can check it out.

https://github.com/Jon1Games/easy-reddit-downloader

**Comment by josephrcox** [comment]
@Jon1Games Your change only delays when you are downloading from the post list file. This may work for you, but it doesn't delay if users are downloading from the prompts at the start of the script (asking subreddit, sorting, post count, etc.)

If you look at my screenshot, I set the delay to 1000ms, and it downloads each post at about 1 second/post. This shows that the delay is working. I can also see that the files are actually being created at about 1/second. This is less noticeable with 250ms but it is definitely working for me. 
<img width="852" alt="Screenshot 2024-03-28 at 10 36 51 AM" src="https://github.com/josephrcox/easy-reddit-downloader/assets/73198556/694651b1-5677-474e-b227-8cc60fdd2c7d">

Your delay also works, but only with the post list. If you are using the post list then my fix also works with that.

**Comment by Jon1Games** [comment]
It wokes fine as long the post list contains under 200 posts. If it´s higher it still crashes.

I can send you an video or show it in an call (Discord for exmaple) if you want, but sadly github isn´t compatible with video files and the error is to long for the terminal to display.

**Comment by josephrcox** [comment]
Is it still an issue even if you manually set the postDelayMilliseconds to something higher like 1000 or 1500?

**Comment by Jon1Games** [comment]
with 1500ms its going to like 300.

**Comment by Jon1Games** [comment]
Got an idear. Maybe you can make it if its and post download list it´s going to use my only post list methode and if its not a post list download use it like right now

**Comment by Jon1Games** [comment]
Tested with ms of 10000 and it crahes at 350 so I think around there is the limit of this method.

**Comment by yellowbikewithbluehandles** [comment]
> Tested with ms of 10000 and it crahes at 350 so I think around there is the limit of this method.

When you say this does that mean after 350 posts you get perma banned or can you download again after a hour or 2 another 350? So if we stay below 350 posts can we just keep archiving at around 350 posts per hour for example?

**Comment by josephrcox** [comment]
The problem is that this will almost always be a risk with using the APIs like this. 

Pro of using the APIs like this: They don't know what user is doing the downloading, and it's really easy to download. 
Con: They can IP block you very easily since you aren't paying to use their API designed for this purpose. 

It may also be possible that they are blocking you specifically for some reason. A VPN (even a free one) may help. 

@yellowbikewithbluehandles I believe he means that it's just stopping for a little bit. It keeps going but temp bans.

**Comment by Jon1Games** [comment]
hello again...
So the temp ban still happends as as we see in the provided log.

I still think you can just add an extra sleep timer to the download loop and make different solutions for the download list and the automatic subredit downloader.

I don`t really remember where you built in the delay, but I feel like it works for everything but the post list.

[log.txt](https://github.com/user-attachments/files/17214007/log.txt)

**Comment by Jon1Games** [comment]
> > Tested with ms of 10000 and it crahes at 350 so I think around there is the limit of this method.
> 
> When you say this does that mean after 350 posts you get perma banned or can you download again after a hour or 2 another 350? So if we stay below 350 posts can we just keep archiving at around 350 posts per hour for example?

It´s a temporary ban, so yes you can start downloading again after a few hours... But if the configured right and applies correct that shoud not happen.

**Comment by Jon1Games** [comment]
#event-14918330621
