### ISSUE TITLE
if the post have many images it well download url not images

### ISSUE THREAD

**Issue by kigy1** [josephrcox/easy-reddit-downloader#91]
thanks for your work

this how to fix it 
edit this code 

for (const child of data.data.children) {
    const post = child.data;
    // Check if the post contains a gallery
    if (post.is_gallery && post.media_metadata) {
        Object.entries(post.media_metadata).forEach(async ([id, media]) => {
            if (media && media.s && media.s.u) {
                const imageUrl = media.s.u.replace(/&amp;/g, '&');
                const fileType = imageUrl.split('.').pop().split('?')[0];
                const fileName = `${sanitizeFileName(post.title)}_${id}.${fileType}`;
                const filePath = `${downloadDirectory}/${fileName}`;

                try {
                    await downloadMediaFile(imageUrl, filePath);
                    console.log(`Downloaded image: ${filePath}`);
                } catch (error) {
                    console.error(`Failed to download image: ${error}`);
                }
            }
        });
    } else {
        // Code for handling other types of posts
        await sleep();
        try {
            await downloadPost(post);
        } catch (e) {
            log(e, true);
        }
    }
}
	} catch (error) {
		// throw the error
		throw error;
	}
}

but after that this Error: EMFILE: too many open files, open
also it is loops and download the file again and again

**Comment by josephrcox** [comment]
Should be closed with #94
